"""
Coaching Engine's typed shapes (Milestone 5) — the "Coaching Engine"
ADR 003 §1/§2 designed and deferred: consumes the CIE's descriptive-only
`AnalysisReport` and produces prescriptive, evidence-cited output. Kept
in its own package, its own models, separate from app/analysis/models.py
— the same separation of concerns ADR 003 built this whole two-engine
architecture around.
"""

from datetime import datetime, timezone

from pydantic import BaseModel, Field


class CoachingInsight(BaseModel):
    """
    One strength or one weakness. `based_on_module` is required, not
    optional — ADR 003 §5's citation discipline ("every recommendation
    must cite the specific module... that motivated it") applies to
    strengths and weaknesses too, not just recommendations: an
    unattributed observation is exactly as unacceptable here as an
    unattributed recommendation.
    """

    message: str
    based_on_module: str


class Recommendation(BaseModel):
    """
    One actionable recommendation. `priority` is a plain positive
    integer, 1 = highest priority — the LLM assigns it directly rather
    than this engine re-deriving an ordering, since only the model has
    read the full qualitative picture behind why one issue matters more
    than another for this specific transcript.
    """

    message: str
    based_on_module: str
    priority: int


class SuggestedExercise(BaseModel):
    """
    A concrete practice exercise targeting a specific weakness.
    `based_on_module` is optional (unlike CoachingInsight/Recommendation)
    because a well-rounded exercise (e.g. "record yourself daily and
    review pacing and structure together") can legitimately target more
    than one dimension at once — forcing a single citation here would
    push the model toward narrower, less useful exercises than it might
    otherwise suggest.
    """

    title: str
    description: str
    based_on_module: str | None = None


class CoachingContent(BaseModel):
    """
    The exact shape `CoachingEngine` validates the LLM's one coaching
    response against (`LLMReasoner.reason(..., schema=CoachingContent)`)
    — everything Milestone 5 asks the Coaching Engine to generate:
    strengths, weaknesses, actionable recommendations, suggested
    exercises, next practice focus, plus `executive_summary` (consumed
    by `CommunicationSummaryGenerator`, app/coaching/summary.py) —
    generated by this same one call rather than a second, dedicated LLM
    request, per this codebase's established "minimize LLM calls"
    discipline (Sprint 4.5.1).
    """

    strengths: list[CoachingInsight]
    weaknesses: list[CoachingInsight]
    recommendations: list[Recommendation]
    suggested_exercises: list[SuggestedExercise]
    next_practice_focus: str
    executive_summary: str


class CoachingReport(BaseModel):
    """
    `CoachingEngine.generate()`'s actual return type — `CoachingContent`
    plus the provenance/context fields the LLM has no business
    generating itself (`transcript_id`, `generated_at`) and `unavailable`
    (ADR 003 §7: which CIE modules couldn't be assessed this run, so the
    Coaching Engine's silence on a dimension is explicit, not
    ambiguous).
    """

    transcript_id: str
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    strengths: list[CoachingInsight]
    weaknesses: list[CoachingInsight]
    recommendations: list[Recommendation]
    suggested_exercises: list[SuggestedExercise]
    next_practice_focus: str
    executive_summary: str

    unavailable: list[str] = Field(default_factory=list)
